### ISSUE TITLE
New Admin Theme: Check box spacing seems off

### ISSUE THREAD

**Issue by sharonmleon** [omeka/plugin-SearchByMetadata#6]
![Screenshot 2021-09-08 at 13-44-01 Configure Plugin Search By Metadata · Workshops · Omeka Admin](https://user-images.githubusercontent.com/741480/132558659-b5ee95f1-ca5d-4c29-8e6c-9d7c99df8bec.png)

**Comment by kimisgold** [comment]
Can you pull from core and hard refresh? I set new default margins for checkboxes and other inputs wrapped in labels in https://github.com/omeka/Omeka/commit/97ccbf1f40344264cdb4b6d8e310a0fe102fc035.

**Comment by sharonmleon** [comment]
Fixed. I pulled but didn't clear the cache. Sorry for the false alarm.
